settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: src
    path: .
    commands:
      install:
        status: true
        method: go build -o /app/main main.go
      run:
        status: true
        method: /app/main
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - .realize
        - vendor